site_name: Pokotarou Docs
theme: readthedocs
pages:
- 'index.md'
- 'basic_usage.md'
- 'pokotarou_v2.md'
- 'getting_started.md'
- 'lets_pokotarou.md'
- 'pokotarou_option.md'
- 'pokotarou_handler.md'
- 'converter.md'
- 'advanced_setting.md'
- 'pipeline_execute.md'
- 'p_tool.md'
- 'license.md'
extra_css:
  - custom.css