site_name: Pokotarou Docs
theme: readthedocs
nav:
- 'index.md'
- 'basic_usage.md'
- 'getting_started.md'
- 'lets_pokotarou.md'
- 'pokotarou_option.md'
- 'pokotarou_handler.md'
- 'converter.md'
- 'advanced_setting.md'
- 'pipeline_execute.md'
- 'license.md'